name: Build & Deploy (PHP)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify PHP files
        run: |
          echo "✅ PHP project - validating files"
          ls -la *.php 2>/dev/null | head -10 || echo "No PHP files in root"
          find . -name "*.php" -not -path "./vendor/*" | head -10

      - name: Create deployment archive
        run: |
          echo "📦 Creating deployment archive..."
          tar -czf /tmp/deploy.tar.gz \
            --exclude='.git' \
            --exclude='.devops' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.gitignore' \
            --exclude='.env' \
            --exclude='*.md' \
            .
          echo "✅ Archive created"

      - name: Upload archive to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          source: "/tmp/deploy.tar.gz"
          target: "/tmp/"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            set -e

            DEPLOY_PATH="/var/www/admin.arkturian.com"
            BACKUP_DIR="/var/backups"
            BACKUP_PREFIX="admin-panel"
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            BACKUP_PATH="$BACKUP_DIR/${BACKUP_PREFIX}-${TIMESTAMP}"

            echo "🎯 Deploy to: $DEPLOY_PATH"

            if [ -d "$DEPLOY_PATH" ]; then
              echo "💾 Creating backup..."
              mkdir -p "$BACKUP_DIR"
              cp -r "$DEPLOY_PATH" "$BACKUP_PATH"
              echo "✅ Backup created: $BACKUP_PATH"
            fi

            echo "🚀 Deploying PHP files..."
            mkdir -p "$DEPLOY_PATH"
            
            # Extract archive directly to deploy path
            tar -xzf /tmp/deploy.tar.gz -C "$DEPLOY_PATH"
            rm /tmp/deploy.tar.gz

            echo "🔒 Setting permissions..."
            chown -R www-data:www-data "$DEPLOY_PATH"
            chmod -R 755 "$DEPLOY_PATH"
            
            # Make writable directories if they exist
            for dir in logs cache uploads tmp; do
              if [ -d "$DEPLOY_PATH/$dir" ]; then
                chmod -R 775 "$DEPLOY_PATH/$dir"
              fi
            done

            echo "✅ Deployment completed successfully!"
            echo "📁 Live at: https://admin.arkturian.com"
            echo "💾 Backup: $BACKUP_PATH"

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "📍 Site: https://admin.arkturian.com"
          echo "📦 Commit: ${{ github.sha }}"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed for commit ${{ github.sha }}"
          echo "Check logs above for details"

